# Generated by Django 5.2.10 on 2026-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transliteration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arabizi", models.TextField()),
                ("darija", models.TextField()),
                ("msa", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
